services:
  cone-db:
    container_name: cone-db
    image: postgres:18.1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=cone
      - POSTGRES_USER=cone
      - POSTGRES_PASSWORD=conepassword
volumes:
  postgres_data: